# -*- coding: utf-8 -*-
# Copyright 2025 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the asa_asa_objects module
"""


class Asa_objectsArgs(object):  # pylint: disable=R0903
    """The arg spec for the asa_asa_objects module
    """

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "object_type": {
                    "type": "str",
                    "required": True,
                    "choices": ["network", "service"],
                },
                "objects": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"required": True, "type": "str"},
                        "description": {"type": "str"},
                        "host": {"type": "str"},
                        "subnet": {"type": "str"},
                        "range": {"type": "str"},
                        "fqdn": {"type": "str"},
                        "fqdn_v4": {"type": "str"},
                        "fqdn_v6": {"type": "str"},
                        "service": {
                            "type": "dict",
                            "options": {
                                "protocol": {"type": "str", "required": True},
                                "source_port": {
                                    "type": "dict",
                                    "options": {
                                        "eq": {"type": "str"},
                                        "gt": {"type": "str"},
                                        "lt": {"type": "str"},
                                        "neq": {"type": "str"},
                                        "range": {
                                            "type": "dict",
                                            "options": {
                                                "start": {"type": "str"},
                                                "end": {"type": "str"},
                                            },
                                        },
                                    }
                                },
                                "destination_port": {
                                    "type": "dict",
                                    "options": {
                                        "eq": {"type": "str"},
                                        "gt": {"type": "str"},
                                        "lt": {"type": "str"},
                                        "neq": {"type": "str"},
                                        "range": {
                                            "type": "dict",
                                            "options": {
                                                "start": {"type": "str"},
                                                "end": {"type": "str"},
                                            },
                                        },
                                    }
                                },
                                "icmpopt": {
                                    "type": "dict",
                                    "options": {
                                        "name": {"type": "str"},
                                        "code": {"type": "str"},
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "replaced",
        },
    }  # pylint: disable=C0301
