---
authors:
  - Ansible Security Community (ansible-security)
dependencies:
  "ansible.netcommon": ">=6.0.0"
license_file: LICENSE
name: asa
namespace: cisco
description: Ansible Security Collection for Cisco ASA devices.
readme: README.md
repository: https://github.com/ansible-collections/cisco.asa
issues: https://github.com/ansible-collections/cisco.asa/issues
tags: [cisco, asa, networking, security]
version: 6.1.0
