---
authors:
  - Ansible Security Community (ansible-security)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: asa
namespace: cisco
readme: README.md
repository: https://github.com/ansible-collections/asa
tags: [cisco, asa, networking, security]
