---
authors:
  - Ansible Security Community (ansible-security)
dependencies:
  "ansible.netcommon": ">=2.5.1"
license_file: LICENSE
name: asa
namespace: cisco
description: Ansible Security Collection for Cisco ASA devices.
readme: README.md
repository: https://github.com/ansible-collections/cisco.asa
issues: https://github.com/ansible-collections/cisco.asa/issues
tags: [cisco, asa, networking, security]
# NOTE(pabelanger): We create an empty version key to keep ansible-galaxy
# happy. We dynamically inject version info based on git information.
version: 4.0.1
